name: Validate PR

on:
  pull_request:
    branches:
    - main
    paths-ignore:
    - README.md
    - '**/README.md'
    - LICENSE
    - CHANGELOG.md
    - docs/**

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      buildConfiguration: 'Release'
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@v1.10.0
      with:
        mongodb-version: '6'

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: >
        dotnet build
        --configuration $buildConfiguration
        --no-restore

    - name: Test
      run: >
        dotnet test
        --configuration $buildConfiguration
        --no-build
        --verbosity normal
        --collect "Code coverage"
