name: Build and Publish

on:
  push:
    # branches:
    # - main
    tags:
    - '*'
    paths-ignore:
    - README.md
    - LICENSE
    - CHANGELOG.md
    - docs/**

env:
  APNSTEST__BUNDLEID: ${{ vars.APNSTEST__BUNDLEID }}
  APNSTEST__DEVICETOKEN: ${{ secrets.APNSTEST__DEVICETOKEN }}
  APNSTEST__ENVIRONMENT: 'Production'
  APNSTEST__KEYID: ${{ secrets.APNSTEST__KEYID }}
  APNSTEST__PRIVATEKEY: ${{ secrets.APNSTEST__PRIVATEKEY }}
  APNSTEST__TEAMID: ${{ vars.APNSTEST__TEAMID }}
  FCMLEGACYTEST__KEY: ${{ secrets.FCMLEGACYTEST__KEY }}
  FCMLEGACYTEST__REGISTRATIONID: ${{ secrets.FCMLEGACYTEST__REGISTRATIONID }}
  FIREBASETEST__CLIENTEMAIL: ${{ secrets.FIREBASETEST__CLIENTEMAIL }}
  FIREBASETEST__DEVICETOKEN: ${{ secrets.FIREBASETEST__DEVICETOKEN }}
  FIREBASETEST__PRIVATEKEY: ${{ secrets.FIREBASETEST__PRIVATEKEY }}
  FIREBASETEST__PROJECTID: ${{ vars.FIREBASETEST__PROJECTID }}
  FIREBASETEST__TOKENURI: ${{ vars.FIREBASETEST__TOKENURI }}

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Required for GitVersion

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'

    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0
      with:
        useConfigFile: true

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
        source-url: https://api.nuget.org/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }}

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@v1.10.0
      with:
        mongodb-version: '7'

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --configuration Release --no-build

    - name: Pack
      run: >
        dotnet pack
        --configuration Release
        --no-build
        --verbosity normal
        --output $GITHUB_WORKSPACE/drop
        -p:PackageVersion=$GITVERSION_NUGETVERSION

    - name: Publish Artifact
      uses: actions/upload-artifact@v3
      with:
        path: ${{ github.workspace }}/drop/*
        name: drop

    - name: Publish to NuGet.org
      if: startsWith(github.ref, 'refs/tags/')
      run: >
        dotnet nuget push "$GITHUB_WORKSPACE/drop/*"
        -k ${{ secrets.NUGET_API_KEY }}
        --skip-duplicate
